USE [master]
GO
/****** Object:  Database [Gogo]    Script Date: 14.10.2021 19:24:31 ******/
CREATE DATABASE [Gogo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Gogo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Gogo.mdf' , SIZE = 2105344KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Gogo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Gogo_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Gogo] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Gogo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Gogo] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Gogo] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Gogo] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Gogo] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Gogo] SET ARITHABORT OFF 
GO
ALTER DATABASE [Gogo] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Gogo] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Gogo] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Gogo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Gogo] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Gogo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Gogo] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Gogo] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Gogo] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Gogo] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Gogo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Gogo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Gogo] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Gogo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Gogo] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Gogo] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Gogo] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Gogo] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Gogo] SET  MULTI_USER 
GO
ALTER DATABASE [Gogo] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Gogo] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Gogo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Gogo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Gogo] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Gogo] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Gogo] SET QUERY_STORE = OFF
GO
USE [Gogo]
GO
/****** Object:  Table [dbo].[Productions]    Script Date: 14.10.2021 19:24:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Productions](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[GeneratorId] [int] NOT NULL,
	[Quantity] [float] NOT NULL,
	[Date] [date] NOT NULL,
	[Time] [time](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[DatesRange]    Script Date: 14.10.2021 19:24:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[DatesRange]
	AS
	SELECT
		MIN(Date) Min,
		Max(Date) Max
	FROM dbo.Productions
GO
/****** Object:  View [dbo].[RowsCount]    Script Date: 14.10.2021 19:24:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[RowsCount]
AS
SELECT COUNT(*) [Count] FROM dbo.Productions
GO
/****** Object:  Table [dbo].[Generator]    Script Date: 14.10.2021 19:24:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Generator](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Energy] [float] NOT NULL,
	[Date] [date] NOT NULL,
	[Time] [time](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Notifications]    Script Date: 14.10.2021 19:24:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Notifications](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Date] [smalldatetime] NOT NULL,
	[Message] [nvarchar](500) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [NonClusteredIndex-20211014-173352]    Script Date: 14.10.2021 19:24:31 ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20211014-173352] ON [dbo].[Productions]
(
	[Date] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [NonClusteredIndex-20211014-175703]    Script Date: 14.10.2021 19:24:31 ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20211014-175703] ON [dbo].[Productions]
(
	[GeneratorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Gogo] SET  READ_WRITE 
GO
